version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zk
    restart: always
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kfk
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9999:9999"
    expose:
      - "9093"
    environment:
        KAFKA_ADVERTISED_HOST_NAME: localhost
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=192.168.1.39 -Dcom.sun.management.jmxremote.rmi.port=9999"
        JMX_PORT: 9999
        KAFKA_CREATE_TOPICS: "test:3:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-eagle:
    image: gui66497/kafka_eagle
    container_name: ke
    restart: always
    depends_on:
      - kafka
    ports:
      - "8048:8048"
    environment:
      ZKSERVER: "zookeeper:2181"
    volumes:
      - ./system-config.properties:/kafka-eagle/conf/system-config.properties
      - ./logs:/kafka-eagle/logs
